//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorServerLocalizationTEST.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorServerLocalizationTEST.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        public static string _000 {
            get {
                return ResourceManager.GetString("000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First text in english.
        /// </summary>
        public static string _001 {
            get {
                return ResourceManager.GetString("001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second text in english.
        /// </summary>
        public static string _002 {
            get {
                return ResourceManager.GetString("002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third text in english.
        /// </summary>
        public static string _003 {
            get {
                return ResourceManager.GetString("003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth text in english.
        /// </summary>
        public static string _004 {
            get {
                return ResourceManager.GetString("004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth text in english.
        /// </summary>
        public static string _005 {
            get {
                return ResourceManager.GetString("005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor Conf 2022.
        /// </summary>
        public static string Blazor_Conf_2022 {
            get {
                return ResourceManager.GetString("Blazor Conf 2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Blazor Localization-En.png.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization in Blazor Server.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
